# Penyelesaian Sistem Persamaan Linear

## menyelesaikan sistem linear menggunakan metode eliminasi gauss

Eliminasi Gauss ([wikipedia](https://id.wikipedia.org/wiki/Eliminasi_Gauss#:~:text=Dalam%20matematika%2C%20eliminasi%20Gauss%20adalah%20algoritma,yang%20digunakan%20untuk%20menyelesaikan%20sistem%20persamaan%20linear.)) adalah algoritma yang di di gunakan untuk menyelsaikan sistem linear, algoritma ini mengubah bentuk persamaan tanpa merubah eliminasi Gauss adalah algoritma yang digunakan untuk menyelesaikan sistem persamaan linear. Algoritma ini terdiri dari serangkaian operasi yang di sebut operasi baris, dilakukan pada matriks koefisien dari sistem persamaan tersebut. Walau akan mengubah bentuk matriks, operasi-operasi tersebut tidak akan mengubah solusi dari sistem persamaan. Hal ini memungkinkan matriks koefisien dibentuk menjadi sebuah matriks segitiga atas, sehingga solusi sistem persamaan dapat ditentukan dengan cukup melakukan eliminasi variabel secara berulang.

operasi baris yang dapat di lakukan:    
- Tukarkan posisi kedua persamaan.
- Kalikan persamaan dengan bilangan apa pun yang bukan nol.
- Gantikan suatu persamaan dengan jumlah persamaan itu sendiri dan kelipatan persamaan lainnya.




Contoh :

$
    2x_1 + 2x_2 = 9 
    2x_1 + 4x_2 = 8  
$

agar membentuk segitiga atas kita perlu mengubah elemeb $matrix_{21}$ menjadi 0, kita akan melakukan operasi baris yaitu mengurangi baris 1 dengan baris 0  
  
$
    \begin{bmatrix}
    2 & 2 \quad | & 9\\
    2 & 4 \quad | & 8
    \end{bmatrix}
    \quad R0 - R1 \implies
    \begin{bmatrix}
    2 & 2 \quad | & 9 \\
    0 & 2 \quad | & -1
    \end{bmatrix}
$  
  
solusi :   
- $0 + 2x_2 = -1 \space \implies \space x_2 = -\frac 12$
- $2x_1 + 2 * -\frac 12 = 9 \space \implies \space x_1 = 5$

$2 * 5 + 4 * (-\frac 12) = 8 \space \implies \space 10 - 2 = 8 \space \implies \space 8 = 8$


## Contoh menyelesaikan sistem linear 3 variable

In [1]:
import numpy as np
# membuat sistem linear
A = np.array([[-1,8,4,7], [5,7,8,-43],[-5,-6,-10,61]])

print(A)

[[ -1   8   4   7]
 [  5   7   8 -43]
 [ -5  -6 -10  61]]


In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [3]:
print(A, "\n")

A1 = RowAdd(A, 2,1,1)
print(A1, "\n")
A2 = RowAdd(A1, 0, 2, -5)
print(A2, "\n")
A3 = RowScale(A2, 2, 1/2)
print(A3, "\n")
A4 = RowAdd(A3, 1, 2, 23)
print(A4, "\n")
A5 = RowScale(A4, 2, -1/61)
print(A5, "\n")

[[ -1   8   4   7]
 [  5   7   8 -43]
 [ -5  -6 -10  61]] 

[[ -1.   8.   4.   7.]
 [  0.   1.  -2.  18.]
 [ -5.  -6. -10.  61.]] 

[[ -1.   8.   4.   7.]
 [  0.   1.  -2.  18.]
 [  0. -46. -30.  26.]] 

[[ -1.   8.   4.   7.]
 [  0.   1.  -2.  18.]
 [  0. -23. -15.  13.]] 

[[ -1.   8.   4.   7.]
 [  0.   1.  -2.  18.]
 [  0.   0. -61. 427.]] 

[[-1.  8.  4.  7.]
 [ 0.  1. -2. 18.]
 [-0. -0.  1. -7.]] 



_persamaanya adalah:_

$-1x_1 + 8x_2 + 4x_3 = 7$  
$1x_2 - 2x_3 = 18$  
$x_3 = -7$  


In [84]:
x3 = -7
x2 = 18 + (2 * x3)
x1 = -(7 - (8 * x2) - (4 * x3))
print(f"""
x1 = {x1}
x2 =  {x2}
x3 = {x3}
""")

# kita akan membuktikanya solusinya apakah benar
print("1. -1x1 + 8x2 + 4x3 = 7")
print("   -1x1 + 8x2 + 4x3 =", (-1 * x1) + (8 * x2) + (4 * x3))
print("2.  5x1 + 7x2 + 8x3 = -43")
print("    5x1 + 7x2 + 8x3 =", (5 * x1) + (7 * x2) + (8 * x3))
print("3. -5x1 - 6x2 - 10x3 = 61")
print("   -5x1 - 6x2 - 10x3 =", (-5 * x1) - (6 * x2) - (10 * x3))



x1 = -3
x2 =  4
x3 = -7

1. -1x1 + 8x2 + 4x3 = 7
   -1x1 + 8x2 + 4x3 = 7
2.  5x1 + 7x2 + 8x3 = -43
    5x1 + 7x2 + 8x3 = -43
3. -5x1 - 6x2 - 10x3 = 61
   -5x1 - 6x2 - 10x3 = 61
