# Matrix Inverse

Inverse matrix adalah kebalikan dari sebuah matriks. Jika suatu matriks A mempunyai invers, matriks A tersebut dapat dikalikan dengan inversnya $(A^{-1})$ untuk menghasilkan matriks identitas. dan jika kita mengalikan $A^{-1}$ dengan vektor hasil akan menghasilkan solusi

In [3]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

## Mencari Matrix inverse persamaan linear 4 variable

$$
  2_{x1} + 3_{x2} + 2_{x3} + 1_{x4} = 18 \\
  1_{x1} + 2_{x2} + 4_{x3} + 3_{x4} = 29 \\
  3_{x1} + 4_{x2} + 2_{x3} + 1_{x4} = 21 \\
  2_{x2} + 3_{x3} + 2_{x4} = 21 \\
$$

In [8]:
import numpy as np

# solusi 
# x1 = 1
# x2 = 2
# x3 = 3
# x4 = 4

M = np.array([[2, 3, 2, 1], [1, 2, 4, 3], [3, 4, 2, 1], [0, 2, 3, 2]])
A = np.array([[2,3,2,1,1,0,0,0], [1,2,4,3,0,1,0,0], [3,4,2,1,0,0,1,0], [0,2,3,2,0,0,0,1]])
print("A \n", A, "\n")

A1 = RowSwap(A, 0, 1)
print("A1 \n", A1, "\n")
A2 = RowAdd(A1, 0, 2, -3)
print("A2 \n", A2, "\n")
A3 = RowAdd(A2, 0, 1, -2)
print("A3 \n", A3, "\n")
A4 = RowScale(A3, 1, -1)
print("A4 \n", A4, "\n")
A5 = RowAdd(A4, 1, 2, 2)
print("A5 \n", A5, "\n")
A6 = RowAdd(A5, 1, 3, -2)
print("A6 \n", A6, "\n")
A7 = RowScale(A6, 2, 1/2)
print("A7 \n", A7, "\n")
A8 = RowAdd(A7, 2, 3, 9)
print("A8 \n", A8, "\n")
A9 = RowAdd(A8, 3, 2, -1)
print("A9 \n", A9, "\n")
A10 = RowAdd(A9, 3, 1, -5)
print("A10 \n", A10, "\n")
A11 = RowAdd(A10, 2, 1, -6)
print("A11 \n", A11, "\n")
A12 = RowAdd(A11, 3, 0, -3)
print("A12 \n", A12, "\n")
A13 = RowAdd(A12, 2, 0, -4)
print("A13 \n", A13, "\n")
A14 = RowAdd(A13, 1, 0 , -2)
print("A14 \n", A14, "\n")

A 
 [[2 3 2 1 1 0 0 0]
 [1 2 4 3 0 1 0 0]
 [3 4 2 1 0 0 1 0]
 [0 2 3 2 0 0 0 1]] 

A1 
 [[1. 2. 4. 3. 0. 1. 0. 0.]
 [2. 3. 2. 1. 1. 0. 0. 0.]
 [3. 4. 2. 1. 0. 0. 1. 0.]
 [0. 2. 3. 2. 0. 0. 0. 1.]] 

A2 
 [[  1.   2.   4.   3.   0.   1.   0.   0.]
 [  2.   3.   2.   1.   1.   0.   0.   0.]
 [  0.  -2. -10.  -8.   0.  -3.   1.   0.]
 [  0.   2.   3.   2.   0.   0.   0.   1.]] 

A3 
 [[  1.   2.   4.   3.   0.   1.   0.   0.]
 [  0.  -1.  -6.  -5.   1.  -2.   0.   0.]
 [  0.  -2. -10.  -8.   0.  -3.   1.   0.]
 [  0.   2.   3.   2.   0.   0.   0.   1.]] 

A4 
 [[  1.   2.   4.   3.   0.   1.   0.   0.]
 [ -0.   1.   6.   5.  -1.   2.  -0.  -0.]
 [  0.  -2. -10.  -8.   0.  -3.   1.   0.]
 [  0.   2.   3.   2.   0.   0.   0.   1.]] 

A5 
 [[ 1.  2.  4.  3.  0.  1.  0.  0.]
 [-0.  1.  6.  5. -1.  2. -0. -0.]
 [ 0.  0.  2.  2. -2.  1.  1.  0.]
 [ 0.  2.  3.  2.  0.  0.  0.  1.]] 

A6 
 [[ 1.  2.  4.  3.  0.  1.  0.  0.]
 [-0.  1.  6.  5. -1.  2. -0. -0.]
 [ 0.  0.  2.  2. -2.  1.  1.  0.]
 [ 

$
\begin{matrix}
    Matrix Inverse = \begin{bmatrix}
        1 & 0.5 & -0.5 & -1 \\
        -2 & -0.5 & 1.5 & 1 \\
        6 & 0 & -4 & -1 \\
        -7 & 0.5 & 4.5 & 1 \\
    \end{bmatrix} *
    Vektor Hasil = \begin{bmatrix}
        18 \\
        19 \\
        21 \\
        21 \\
    \end{bmatrix}
    = solusi = \begin{bmatrix}
    1 \\
    2 \\
    3 \\
    4
    \end{bmatrix}
\end{matrix}
$

In [5]:
A_inverse = np.array([[1, 0.5, -0.5, -1], [-2, -0.5, 1.5, 1], [6, 0, -4, -1], [-7, 0.5, 4.5, 1]])
b = np.array([[18], [29], [21], [21]])

result = A_inverse @ b

# perkalian antara matrix inverse dan vektor hasil menghasilkan solusi jadi perhitungan kita benar
print(result)

[[1.]
 [2.]
 [3.]
 [4.]]


In [9]:
print(np.dot(M, A_inverse))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
