# Operasi Operasi Matrix

1. **Matriks dalam bentuk apa pun dapat dikalikan dengan skalar c,d**  
Hasilnya salah semua elemen matrix dikalikan dengan skalar tersebut Dengan menggunakan notasi, subskrip, kita akan ditulis dengan
  
$\hspace{1.6em} (cA)_{ij} = ca_{ij}$  
$\hspace{1.6em} (c + d)A = cA + dA$  
$\hspace{1.6em} c(dA) = (cd)A$  
$\hspace{1.6em} c(A + B) = cA + cB$  
$\hspace{1.6em} A \space terdapat \space -\space A,sehingga\space A + (-A) = 0$  
$\hspace{1.6em}$ Code:
```python
import numpy as np # mengimport numpy librari dan meangalisakan nya dengan nama np

A = np.array([[1, 3], [3, 5]]) # matrix yang berukuran 2 x 2
skalar = 3
print("A = ", A)
print("skalar = ", slakar)
print()

print("A * skalar = ",A * skalar)

```
$\hspace{1.6em}$ Output: 
```python
A =  [[1 3]
 [3 5]]
skalar =  3

A * skalar =  [[ 3  9]
 [ 9 15]]

```
  
2. **Matriks yang ukuranya sama dapat dijumlahkan**  
Hasilnya adalah semua elemen A ditambahkan dengan semua elemen B, dengan baris dan kolom yang sama 
  
$\hspace{1.6em} (A + C)_{ij} = a_{ij} + c_{ij}$  
$\hspace{1.6em} A + 0 = A \space dimana \space 0 \space matrix \space 0$  
$\hspace{1.6em} A + B = B + A$  
$\hspace{1.6em} (A + B) + C = A + (B + C)$   
$\hspace{1.6em}$ Code:

```python
import numpy as np # mengimport numpy librari dan meangalisakan nya dengan nama np

A = np.array([[1, 3], [3, 5]]) # matrix yang berukuran 2 x 2
B = np.random.randint(10, size=(2,2)) # membuat matrix random dengan nilai element maximal 10 dan ukuran 4 x 4 secara random

print("A: \n", A)
print("B: \n", B)
print()

# pastikan ukuran dari kedua matrix sama
print("A + B: \n", A + B)
print()
```
$\hspace{1.6em}$ Output: 
```python
A: 
 [[1 3]
 [3 5]]
B: 
 [[8 6]
 [1 0]]

A + B: 
 [[9 9]
 [4 5]]
```
  
3. **Kolom dari Matrix A adalah sama dengan banyaknya baris di Matrix B Matrix dapat dikalikan**  
Hasilnya adalah matrix $AB$ dengan baris sama dengan matrix $A$ dan kolom sama dengan matrix $B$, $(AB)_{ij}$ perkalian antara setiap element baris $A$ dikalikan setiap element kolom $B$
  
$\hspace{1.6em} (AB)_{ij} =  \sum_{k=1}^{n} a_{ik} b_{kj}$  
  
$\hspace{1.6em}$ karakteristik perkalian matrix $A, B, C$

$\hspace{1.6em} \cdotp $ $c(AB) = (cA)B = A(cB)$  
$\hspace{1.6em} \cdotp $ $(AB)C = A(BC)$  
$\hspace{1.6em} \cdotp $ $A(B + C) = AB + AC$  
$\hspace{1.6em} \cdotp $ $(B + C)A = BA + CA$ 
```{note}
di perkalian matrix tidak menerapkan hukum komutatif jadi $AB \space \neq \space BA$
```
$\hspace{1.6em}$ Code:
```python
import numpy as np

A = np.array([[2,1,3], [2,1,2]])
B = np.array([[1,3], [2,2], [1,2]])

print("A: ", A)
print()
print("B: ", B)
print()

def multipleMatrix(A, B):
    if A.shape[1] != B.shape[0]: # memastikan matrix memenuhi syarat perkalian matrix yaitu kolom A sama dengan baris B, agar tidak error
        print("syarat tidak terpenuhi")
        return False
    n = A.shape[1] # ini adalah menentukan nilai n seperti di rumus dapat menggunakan kolom matrix A atau menggunakan baris matrix B
    res = [] # membuat array kosong untuk menampung hasilnya
    for i in range(A.shape[0]): # melakukan iterasi pada baris, menggunakan baris dari matrix A
        row = [] # menampung setiap row
        for j in range(B.shape[1]): # melakukan iterasi pada kolom, menggunakan kolom dari matrix B 
            e = 0 # menampung total setiap element
            for k in range(n): # melakukan iterasi sesuai dengan rumus 0 - n
                e = e + (A[i][k] * B[k][j]) # melakukan operasi sesuai rumus
            row.append(e) # memasukan setiap total element ke row

        res.append(row) # memasukan setiap row ke res
    return res # hasil akan memiliki ukuran baris sama dengan baris dari kolom A dan kolom sama dengan kolom B

hasil = multipleMatrix(A, B)
print("AB: ", hasil)
```
$\hspace{1.6em}$ Output: 
```python
A:  [[2 1 3]
 [2 1 2]]

B:  [[1 3]
 [2 2]
 [1 2]]

AB:  [[7, 14], [6, 12]]

```