# Matrix Transponse

Transpose Matrix A adalah $A^T$, yang dimana kolom kolom kolom $A$ merupakan baris baris matrix $A^T$, $A_{kolom\ baris}$ merupakan elemen tranpose dari $A$   
$
\begin{matrix}
    \\
    A = \begin{bmatrix}
    3 & 4 & 5 \\
    5 & 6 & 7 \\
    3 & 4 & 5
    \end{bmatrix}
    A^T = \begin{bmatrix}
    3 & 5 & 3 \\
    4 & 6 & 4 \\
    5 & 7 & 5 
    \end{bmatrix} \\
\end{matrix}
$

**Karakteristik Tranpose**

$1.\quad (A^T)^T = A$  
$2.\quad (A + B)^T = A^T + B^T$  
$3.\quad (cA)^T = cA^T$  
$4.\quad (AB)^T = A^T * B^T$ 

In [4]:
# mancari matrix tranpose menggunakan numpy

import numpy as np
A = np.array([[3,4,5], [5,6,7], [3,4,5]])

A_transponse = A.transpose()

print("A = ", A)
print()
print("A tranponse = ", A_transponse)

A =  [[3 4 5]
 [5 6 7]
 [3 4 5]]

A tranponse =  [[3 5 3]
 [4 6 4]
 [5 7 5]]


## Matrix simetris dan Matrix skew simetris 

matrix simetris adalah matrix yang jika matrix A = $A^T$  
matrix skew simetris adalah matrix yang matrix $A^T$ = -A  

$
\begin{matrix}
    Matrik \space Simetris : \quad
    A   \begin{bmatrix}
            3 & 4 & 5 \\
            4 & 7 & 6 \\
            5 & 6 & 8
        \end{bmatrix} \quad
        = \quad
    A^T   \begin{bmatrix}
            3 & 4 & 5 \\
            4 & 7 & 6 \\
            5 & 6 & 8
        \end{bmatrix}
\end{matrix}
$  

$
\begin{matrix}
    Matrik \space Skew \space Simetris : \quad
   A =  \begin{bmatrix}
    0 & 4 & 5 \\
    -4 & 0 & 8 \\
    -5 & -8 & 0
    \end{bmatrix}
    A^T = \begin{bmatrix}
    0 & -4 & -5 \\
    4 & 0 & -8 \\
    5 & 8 & 0
    \end{bmatrix} = -A 
\end{matrix}
$