# Matrix elementer

matrix elementer adalah matrix yang di dapat dari satu operasi baris elementer pada suatu matrix identitas seperti:  
$
\begin{matrix} \\
    \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
    \end{bmatrix}
    R_1 \iff R_2 \implies
    \begin{bmatrix}
    0 & 1 & 0 \\
    1 & 0 & 0 \\
    0 & 0 & 1
    \end{bmatrix} \\
    \\
    \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
    \end{bmatrix}
    R_1 -7R_3 \implies
    \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    -7 & 0 & 1
    \end{bmatrix}
\end{matrix} \\
$

matrix yang ditransformasikan kita nyatan sebagai E, jika E di kalikan ke kiri pada matrix A maka hasil EA akan sama seperti jika A di lakukan operasi baris elementer yang sama


In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

In [3]:
import numpy as np

matriks_identitas = np.array([[1,0,0], [0,1,0], [0,0,1]])

E = RowSwap(matriks_identitas, 2, 1)

A = np.array([[2,3,5], [4,2,3], [1,2,3]])

EA = np.dot(E, A)

A1 = RowSwap(A, 2, 1)

print("E : ", E)
print()
print("EA : ", EA)
print()
print("A1 : ", A1)
print()
print("Apakah A1 = EA?", EA == A1)



E :  [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

EA :  [[2. 3. 5.]
 [1. 2. 3.]
 [4. 2. 3.]]

A1 :  [[2. 3. 5.]
 [1. 2. 3.]
 [4. 2. 3.]]

Apakah A1 = EA? [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
