# Formula Determinan

## Ekspansi Kofaktor
Ekspansi Kofaktor adalah salah satu metode mencari determinan suatu matriks, di mana dalam metode ini memanfaatkan kofaktor. Dalam metode ini dikenal istilah Minor Elemen yang ditulis $M_{ij}$ dan kofaktor elemen yang ditulis $c_{ij}$.   

Kita akan mencari determinan dari matriks 4x4 dengan formula determinan ekspansi kofaktor

$
\begin{matrix}
    Matrix A = \begin{bmatrix} 
      1&2&3&3 \\
      2&2&2&2 \\
      3&2&1&2 \\
      3&1&1&1 \\
    \end{bmatrix} \\
  \\
\end{matrix} \\  
$  

$
Menggunakan \space Baris \space 2
$  
$
= a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} + a_{24}c_{24} \\
$  
  
$c_{21} = (-1)^{2+1}det(M_{21})$  
  
$c_{22} = (-1)^{2+2}det(M_{22})$  
  
$c_{23} = (-1)^{2+3}det(M_{23})$  
  
$c_{24} = (-1)^{2+4}det(M_{24})$

Kita perlu mencari determian matrix-matrix minor dari matriks A sebagai berikut


**Determinan M21**  
Mencari determinan dari $M_{21}$ dengan Ekspansi kofaktor  

$
\begin{matrix} \\
     M_{21} \space = \begin{bmatrix} 
    2&3&3 \\
    2&1&2 \\
    1&1&1 \\
  \end{bmatrix} \\ \\
\end{matrix} \\
$

$
Menggunakan \space Baris \space 2
$  
$
= m_{21}c_{21} + m_{22}c_{22} + m_{23}c_{23}
$  

$
c_{21} = (-1)^{2+1}det(M_{21 \space dari \space matriks M_{21}})
$  
$
\quad \space = (-1)^{2+1}det(
\begin{matrix}
  \begin{bmatrix}
    3&3 \\
    1&1
  \end{bmatrix}) 
\end{matrix} 
$  
$
\quad \space= -1.0
$  


$
c_{22} = (-1)^{2+2}det(M_{22 \space dari \space matriks M_{21}})
$  
$
\quad \space = (-1)^{2+2}det
\begin{matrix}(
\begin{bmatrix}
    2&3 \\
    1&1
\end{bmatrix}) 
\end{matrix} 
$  
$
\quad \space= 1.-1
$  

$
c_{23} = (-1)^{2+3}det(M_{23 \space dari \space matriks M_{21}})
$  
$
\quad \space = (-1)^{2+3}det
\begin{matrix}(
\begin{bmatrix}
    2&3 \\
    1&1
\end{bmatrix})
\end{matrix} 
$  
$
\quad \space= -1.-1
$  

$
m_{21}c_{21} + m_{22}c_{22} + m_{23}c_{23}
$  
$
= 2.(-1).0 + 1.(1).(-1) + 2.(-1).(-1) 
$  

$
det(M_{21}) \space = 0 - 1 + 2 =  1 
$  
Determinan $M_{21}$ adalah **1**  

**Determinan M22**  
Mencari determinan dari $M_{22}$ dengan Ekspansi kofaktor  
$
\begin{matrix} \\
 M_{22} \space  = \begin{bmatrix} 
    1&3&3 \\
    3&1&2 \\
    3&1&1 \\
  \end{bmatrix} \\ \\
\end{matrix} \\
$  


$
Menggunakan \space Baris \space 2
$  
$
= m_{21}c_{21} + m_{22}c_{22} + m_{23}c_{23} 
$

$
c_{21} = (-1)^{2+1}det(M_{21 \space dari \space matriks M_{22}})
$  
$
\quad \space= (-1)^{2+1} det
\begin{matrix}(
  \begin{bmatrix}
   3&3 \\
   1&1 
  \end{bmatrix})
\end{matrix} 
$  
$
\quad \space= -1.0
$  

$
c_{22} = (-1)^{2+2}det(M_{22 \space dari \space matriks M_{22}})
$  
$
\quad \space = (-1)^{2+2} det 
\begin{matrix}(
  \begin{bmatrix}
   1&3 \\
   3&1
  \end{bmatrix})
\end{matrix} 
$  
$
\quad \space= 1.-8
$  

$
c_{23} = (-1)^{2+3}det(M_{23 \space dari \space matriks M_{22}})
$  
$
\quad \space= (-1)^{2+3} det
\begin{matrix}(
  \begin{bmatrix}
    1&3 \\
    3&1
  \end{bmatrix})
\end{matrix}  
$  
$
\quad \space = -1.-8
$  

$
m_{21}c_{21} + m_{22}c_{22} + a_{23}c_{23}
$  
$
= 3.(-1).0 + 1.(1).(-8) + 2.(-1).(-8) 
$  

$
det(M_{22}) \space= 0 - 8 + 16 =  8
$  
Determinan dari $M_{22}$ adalah **8** 

**Determinan M23**  
Mencari determinan dari $M_{23}$ dengan Ekspansi kofaktor  
$
\begin{matrix} 
 M_{23} \space = \begin{bmatrix} 
    1&2&3 \\
    3&2&2 \\
    3&1&1 \\
  \end{bmatrix} 
\end{matrix} 
$  

$
Menggunakan \space Baris \space 2
$  
$
= m_{21}c_{21} + m_{22}c_{22} + m_{23}c_{23}
$  

$
c_{21} = (-1)^{2+1}det(M_{21 \space dari \space matriks M_{23}})
$  
$
\quad \space \space= (-1)^{2+1} det
\begin{matrix}(
  \begin{bmatrix}
   2&3 \\
   1&1 
  \end{bmatrix})
\end{matrix}  
$  
$
\quad \space = -1.-1
$  

$
c_{22} = (-1)^{2+2}det(M_{22 \space dari \space matriks M_{23}})
$  
$
\quad \space \space= (-1)^{2+2} det 
\begin{matrix}(
  \begin{bmatrix}
   1&3 \\
   3&1
  \end{bmatrix})
\end{matrix}  
$  
$
\quad \space=  1.-8
$  

$
c_{23} = (-1)^{2+3}det(M_{23 \space dari \space matriks M_{23}})
$  
$
\quad \space= (-1)^{2+3} det
\begin{matrix}(
  \begin{bmatrix}
    1&2 \\
    3&1
  \end{bmatrix})
\end{matrix}  
$  
$
\quad \space = -1.-5
$  

$
m_{21}c_{21} + m_{22}c_{22} + m_{23}c_{23}
$  
$
= 3.(-1).(-1) + 2.(1).(-8) + 2.(-1).(-5)
$  

$
det(M_{23}) \space = 3 - 16 + 10 = -3
$  
Determinan dari $M_{23}$ adalah **-3**  

**Determinan M24**  
Mencari determinan dari $M_{24}$ dengan Ekspansi kofaktor  
$
\begin{matrix} \\
  M_{24} \space = \begin{bmatrix} 
    1&2&3 \\
    3&2&1 \\
    3&1&1 \\
  \end{bmatrix} \\ \\
\end{matrix} \\
$  

$
Menggunakan \space Baris \space 2  
$  
$
= m_{21}c_{21} + m_{22}c_{22} + m_{23}c_{23}
$  

$
c_{21} = (-1)^{2+1}det(M_{21 \space dari \space matriks M_{24}})
$  
$
\quad \space  = (-1)^{2+1} det
\begin{matrix}(
  \begin{bmatrix}
   2&3 \\
   1&1 
  \end{bmatrix})
\end{matrix} 
$  
$
\quad \space= -1.-1 
$  

$
c_{22} = (-1)^{2+2}det(M_{22 \space dari \space matriks M_{24}})
$  
$
\quad \space = (-1)^{2+2} det 
\begin{matrix}(
  \begin{bmatrix}
   1&3 \\
   3&1
  \end{bmatrix})
\end{matrix} 
$  
$
\quad \space= 1.-8
$  

$
c_{23} = (-1)^{2+3}det(M_{23 \space dari \space matriks M_{24}})
$  
$
\quad \space  = (-1)^{2+3} det
\begin{matrix}(
  \begin{bmatrix}
    1&2 \\
    3&1
  \end{bmatrix})
\end{matrix} 
$  
$
\quad \space= -1.-5
$  

$
m_{21}c_{21} + m_{22}c_{22} + m_{23}c_{23}
$  
$
 = 3.(-1).(-1) + 2.(1).(-8) + 1.(-1).(-5)
$  

$
det(M_{24}) \space  = 3 - 16 + 5 = -8
$  
Determinan dari $M_{24}$ adalah **-8** 

**Langkah terakhir Mencari Determinan A**  
    
$
det(M_{21}) = 1  
$

$
det(M_{22}) = 8 
$

$ 
det(M_{23}) = -3  
$

$
det(M_{24}) = -8  
$  

Subtisusi kan nilai nilai determinan dari Matriks-matriks minor  

$
c_{21} = (-1)^{2+1}det(M_{21}) = -1.1  
$

$
c_{22} = (-1)^{2+2}det(M_{22}) = 1.8
$  

$
c_{23} = (-1)^{2+3}det(M_{23}) = -1.-3
$  

$
c_{24} = (-1)^{2+4}det(M_{24}) = 1.-8
$  

$
a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} + a_{24}c_{24}
$  
$
= 2.(-1).1 + 2.1.8 + 2.(-1).(-3) + 2.1.(-8) \\
$  

$
det(A) = -2 + 16 + 6 - 16 = 4
$    
  
**Jadi Determinan dari Matriks A = 4**

**Kita akan membuktikanya dengan python apakah benar determinan A = 4**

In [17]:
import numpy as np

A = np.array([[1,2,3,3], [2,2,2,2], [3,2,1,2], [3,1,1,1]])
detA = np.linalg.det(A)
print("A: \n", A)
print()
print("Determinan A : ", round(detA))
print("Hasilnya sama dengan perhitungan manual kita menggunakan formula determinan ekspansi kofaktor")

A: 
 [[1 2 3 3]
 [2 2 2 2]
 [3 2 1 2]
 [3 1 1 1]]

Determinan A :  4
Hasilnya sama dengan perhitungan manual kita menggunakan formula determinan ekspansi kofaktor
