# Aljabar Linear Matrik

## Matrix

- Matrix adalah sususan bilangan, simbol, atau expresi yang disusun dalam baris dan kolom [wikipedia matriks](https://id.wikipedia.org/wiki/Matriks_(matematika)), Contoh :  
$
\begin{matrix}
    \\
    A = \begin{bmatrix}
        1 & 3 \\
        2 & 1
    \end{bmatrix}
    \qquad
    B = \begin{bmatrix}
        3 & 0 & 4 \\
        -1 & -2 & 1
    \end{bmatrix}
    \qquad
    C = \begin{bmatrix}
        1 \\ 
        3 \\
        9
    \end{bmatrix}
    \\
    \\
\end{matrix}
$
- Dimensi atau ukuran matrix adalah baris x kolim, contoh matriks $B$ memili ukuran $2x3$ 
- Matriks yang hanya memiliki 1 kolom, seperti C, biasa disebut vektor. 
- Elemen matriks dinyatakan dengan huruf kecil dengan subskrip untuk menunjukkan posisi entri dalam matriks.  
    - Contoh  $b_{12}$ adalah B baris 1 dan kolom 2, berarti $b_{12} = 0$  
    - Secara umum, kita mungkin menggunakan variabel di subskrip, seperti $a_{ij}$ artinya elemen dari a baris $_I$ dan kolom $_j$



In [1]:
# Membuat Matrix dengan numpy
import numpy as np 
A = np.array([[1, 3], [3, 5]]) # matrix yang berukuran 2 x 2
B = np.random.randint(10, size=(4,4)) # membuat matrix random dengan nilai element maximal 10 dan ukuran 4 x 4
print("A = ", A)
print()
print("B = ", B)

A =  [[1 3]
 [3 5]]

B =  [[6 0 1 7]
 [8 9 7 6]
 [1 5 2 2]
 [2 8 4 5]]
