# Determinan
determinan adalah nilai skalar yang dihasilkan fungsi dari entri-entri suatu matriks persegi. Determinan dari matriks A umumnya dinyatakan dengan notasi det(A), det A, atau |A|. Determinan dapat dianggap sebagai faktor penskalaan transformasi yang digambarkan oleh matriks. Nilai determinan mencirikan beberapa sifat dari matriks tersebut, dan peta linear yang diwakili oleh matriks tersebut.

## Sifat Sifat determinant



In [121]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [122]:
import numpy as np
A = np.array([[2, 3], [2, -1]])
B = np.array([[2,2,1], [2,1,2], [4,2,2]])
C = np.array([[1,0], [0,1]])
D = np.array([[1,0,0], [0,1,0], [0,0,1]])
E = np.array([[1,4], [1,1]])
F = np.array([[3,1], [2,1]])

- Determinan dari matrix indentitas adalah 1

In [123]:
print("Matriks C = \n", C, ": determinan nya adalah", np.linalg.det(C))
print()
print("Matriks D = \n", D,": determinan nya adalah", np.linalg.det(D))


Matriks C = 
 [[1 0]
 [0 1]] : determinan nya adalah 1.0

Matriks D = 
 [[1 0 0]
 [0 1 0]
 [0 0 1]] : determinan nya adalah 1.0


-
$
det(C) = det(AB) = de(A).det(B) \\
det(I) = det(A).det(A^{-1}) \\
det(A^{-1}) = 1/det(A) \\
$

In [124]:
G = np.dot(E, F)
detE = np.linalg.det(E)
detF = np.linalg.det(F)
detE_F = detE * detF
detG = np.linalg.det(G)
print(round(detG))
print(round(detE_F))

-3
-3


In [125]:
print()
A_inverse = np.linalg.inv(A)
B_inverse = np.linalg.inv(B)
detA = np.linalg.det(A)
detB = np.linalg.det(B)
detA_inverse = np.linalg.det(A_inverse)
detB_inverse = np.linalg.det(B_inverse)
print("det(A) * det(B) : ",np.dot(detA, detA_inverse))
print("det(A) * det(B) : ",np.dot(detA, detA_inverse))


det(A) * det(B) :  1.0
det(A) * det(B) :  1.0


- Menukar baris dan kolom pada matriks akan merubah tanda determinan

In [89]:
A = np.array([[1,4,2], [1,1,1], [3,2,1]])
B = np.array([[4,1, 2], [1,1,1], [2,3,1]])
detA = np.linalg.det(A)
print(round(detA))
A1 = RowSwap(A, 0, 1)
detA1 = np.linalg.det(A1)
detB1 = np.linalg.det(B)
print(round(detA1))
print(round(detB1))


5
-5
-5


- jika matriks memiliki baris atau kolom kelipatan dari suatu baris atau kolom yang lain pada matriks maka determinan nya sama dengan 0

In [87]:
A = np.array([[1,4,2], [2,8,4], [3,2,1]])
B = np.array([[1,2,1], [4,8,4], [1,4,1]])
detA = np.linalg.det(A)
detB = np.linalg.det(B)
print(detA)
print(detB)

0.0
0.0


- jika K merupakan Skalar maka dan A adalah matriks ukuran $_{nxn} maka $ $determinan(K A) \space =\space K^n * determinan(A)$
- jika T merupakan Skalar dan A adalah matriks maka $determinan((K*A)[0]) \space = \space T * det(A)$

In [98]:
K = 2
A = np.array([[1,4,2], [1,1,1], [3,2,1]])
K_A = np.dot(K, A)
detA = np.linalg.det(A)
detK_A = np.linalg.det(K_A)
detK_AM = np.dot(2 ** 3, round(detA))
print(detK_A)
print(detK_AM)

40.0
40


In [103]:
T = 2
B = np.array([K_A[0]])
print(B)
detBM = np.dot(T, detA)
print(round(detBM))

[[2 8 4]]
10


In [108]:
A = np.array([[1,4,2], [0,4,1], [0,0,1]])
B = np.array([[2,3,1,2], [0,1,2,1], [0,0,5,2], [0,0,0,3]])
detA = np.linalg.det(A)
detB = np.linalg.det(B)
detAM = A[0][0] * A[1][1] * A[2][2]
detBM = B[0][0] * B[1][1] * B[2][2] * B[3][3]
print(detA)
print(detAM)
print(round(detB))
print(detBM)

4.0
4
30
30


- jika melakukan operasi baris elementer tidak akan merubah nilai determinan

In [116]:
A = np.array([[1,4,2], [1,1,1], [3,2,1]])
A1 = RowAdd(A, 0, 1, -1)
A2 = RowAdd(A1, 0, 2, -3)
A3 = RowAdd(A2, 1,2, -1/3)
A4 = RowAdd(A3, 1, 2, -3)
detA4 = np.linalg.det(A4)
print(round(detA4))

5


- determinan A tranpose = determinan A
$$
det(A^T) = det(A)
$$

In [120]:
A = np.array([[1,4,2], [1,1,1], [3,2,1]])
AT = A.transpose()
detAT = np.linalg.det(AT)
detA = np.linalg.det(A)
print(round(detAT))
print(round(detA))

5
5
