# Eigen Value Eigen Vector

**Definisi** 

Jika A adalah $nxn$ maka vektor tidak nol $x$ dinamakan vektor eigen dari A nika $Ax$ adalah kelipan skalar dari X yakni   
  
Ax = $ \lambda X$  
  
Skalar $\lambda$ dinamakan nilai eigen dari A dan x dikatakan vektor eigen yang bersesuaian dengan $\lambda$

Adapun syarat bahwa eigen vektor adalah taknol diberlakukan untuk menghindari kasus yang tidak penting seperti A0 = $\lambda 0$, yang mana berlaku untuk setiap A dan $\lambda$

Ax = λx  
Ax: vektor x setelah transformasi linier  
λx: perkalian bilangan riel dari x, i.e. peregangan dari vektor x.
Transformasi linier untuk eigenvector menghasilkan peregangan vektor
sebanyak eigenvalue kali.  

**Contoh**  
  
Hitung eigen value dan eigen vector dari matrik A  
  
$$
\begin{matrix}
    A = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
\end{matrix}
$$

solusi:  

$
\begin{matrix}
    A - \lambda = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    \lambda \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad
\quad
\begin{matrix}
    = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    \begin{bmatrix}
        \lambda & 0 \\
        0 & \lambda \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad
\quad
\begin{matrix}
    = \begin{bmatrix}
        3 - \lambda & 5 \\
        4 & 2 - \lambda \\
    \end{bmatrix}
\end{matrix}
$

$
det(A - \lambda) = (3 - \lambda) (2 - \lambda) - 20 \\ 
$  

$
\qquad \qquad \quad = \lambda^2 + 6 - 2 \lambda - 3 \lambda - 20 \\
$  

$
\qquad \qquad \quad = \lambda^2 - 5 \lambda - 14
$  


$
\lambda^2 - 5 \lambda - 14 = 0 \\
$  
$
(\lambda - 7) (\lambda + 2) = 0 \\
$  
$
\lambda = 7 \space dan \space -2 
$  

$Ax = 7x \space dan \space Ax = -2x$  
  
Untuk $\lambda = -2$  
  
$
A - (-2)! = \begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    +
    2 \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad \qquad \quad
= \begin{matrix}
    \begin{bmatrix}
        5 & 5 \\
        4 & 4 \\
    \end{bmatrix}
\end{matrix}
$

dari matrix di atas di peroleh persamaan berikut

$x1 + x2 = 0$  
$x1 = -x2$  
$1.1 = -1.-1$  
$x1 = 1$  
$x2 = -1$  
  
$
\begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
        1 \\
        -1
    \end{bmatrix}
    = \begin{bmatrix}
        -2 \\
         2
    \end{bmatrix}
\end{matrix}
$  
  
untuk $\lambda = 7$  

$  
A - 7! = \begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    7 \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  
    
$
\qquad \qquad \quad
= \begin{matrix}
    \begin{bmatrix}
        -4 & 5 \\
        4 & -5 \\
    \end{bmatrix}
\end{matrix}
$

dari matrix di atas di dapatkan persamaan:
$-4x1 + 5x2 = 0$  
$5x2 = 4x1$  
$x1 = 1.25$  
$x2 = 1$  
  
$
\begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
        1.25 \\
        1
    \end{bmatrix}
    = \begin{bmatrix}
        8.75 \\
        7
    \end{bmatrix}
\end{matrix}
$  


eignvalue = [7, -2]  
eignvector = [[1,1], [1,-1]]
  
untuk $\lambda = $ 7 dan $x =$ [1,1]  
   
$
\begin{matrix}
    A x = \begin{bmatrix}
       8.75 \\
       7   
    \end{bmatrix}
    =
    \lambda x = \begin{bmatrix}
        8.75 \\
        7
    \end{bmatrix}
\end{matrix}
$

untuk $\lambda = $ -2 dan $x =$ [1,-1]  
  

$
\begin{matrix}
    A x = \begin{bmatrix}
       -2 \\
        2  
    \end{bmatrix}
    =
    \lambda x = \begin{bmatrix}
        -2 \\
         2
    \end{bmatrix}
\end{matrix}
$



Menghitung eignvalue dan eignvector dengan numpy

In [2]:
# Menghitung eigenvalue dan eigenvector dengan numpy


# matrixs ukuran 2x2
import numpy as np

A = np.array([[3,5], [4,2]])
eign = np.linalg.eig(A)

print("eignvalue: ", eign[0])
print("eignevector: ", eign[1].round())

# matriks ukuran 3 x 3

B = np.array([[3,2,4], [1,2,3], [4,3,1]])
eign2 = np.linalg.eig(B)

print("eignvalue: ", eign2[0])
print("eignvector: ", eign2[1].round())

print()

eignvalue:  [ 7. -2.]
eignevector:  [[ 1. -1.]
 [ 1.  1.]]
eignvalue:  [ 7.74846299  0.91919537 -2.66765836]
eignvector:  [[-1. -1. -0.]
 [-0.  1. -0.]
 [-1. -0.  1.]]
4.0


Implementasi eignvalue dan eignvector

In [12]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
x = iris["data"]
y = iris["target"]

x_ = x - x.mean(axis=0)
u, sigma, vt = np.linalg.svd(x_, full_matrices=False)

print(x.shape, y.shape)
print((x_ @ vt.T), sigma**2 / (x.shape[0] - 1))

(150, 4) (150,)
[[-2.68412563e+00 -3.19397247e-01  2.79148276e-02  2.26243707e-03]
 [-2.71414169e+00  1.77001225e-01  2.10464272e-01  9.90265503e-02]
 [-2.88899057e+00  1.44949426e-01 -1.79002563e-02  1.99683897e-02]
 [-2.74534286e+00  3.18298979e-01 -3.15593736e-02 -7.55758166e-02]
 [-2.72871654e+00 -3.26754513e-01 -9.00792406e-02 -6.12585926e-02]
 [-2.28085963e+00 -7.41330449e-01 -1.68677658e-01 -2.42008576e-02]
 [-2.82053775e+00  8.94613845e-02 -2.57892158e-01 -4.81431065e-02]
 [-2.62614497e+00 -1.63384960e-01  2.18793179e-02 -4.52978706e-02]
 [-2.88638273e+00  5.78311754e-01 -2.07595703e-02 -2.67447358e-02]
 [-2.67275580e+00  1.13774246e-01  1.97632725e-01 -5.62954013e-02]
 [-2.50694709e+00 -6.45068899e-01  7.53180094e-02 -1.50199245e-02]
 [-2.61275523e+00 -1.47299392e-02 -1.02150260e-01 -1.56379208e-01]
 [-2.78610927e+00  2.35112000e-01  2.06844430e-01 -7.88791149e-03]
 [-3.22380374e+00  5.11394587e-01 -6.12996725e-02 -2.16798118e-02]
 [-2.64475039e+00 -1.17876464e+00  1.51627524e