# Cofaktor
Ekspansi Kofaktor adalah salah satu metode mencari determinan suatu matriks, di mana dalam metode ini memanfaatkan kofaktor. Dalam metode ini dikenal istilah Minor Elemen yang ditulis $M_{ij}$ dan kofaktor elemen yang ditulis $c_{ij}$.   

Kita akan mencari determinan dari matriks 4x4 dengan formula determinan ekspansi kofaktor

$
\begin{matrix}
    Matrix A = \begin{bmatrix} 
      2&1&3&1 \\
      3&2&1&3 \\
      4&2&3&2 \\
      2&3&1&1 \\
    \end{bmatrix} \\
  \\
\end{matrix} \\  
$  

$
Menggunakan \space Baris \space 2 = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} + a_{24}c_{24} \\
$  
  
$c_{21} = (-1)^{2+1}det(M_{21})$  
  
$c_{22} = (-1)^{2+2}det(M_{22})$  
  
$c_{23} = (-1)^{2+3}det(M_{23})$  
  
$c_{24} = (-1)^{2+4}det(M_{24})$

Kita perlu mencari determian matrix-matrix minor dari matriks A sebagai berikut


**Determinan M21**  
Mencari determinan dari $M_{21}$ dengan Ekspansi kofaktor  

$
\begin{matrix} \\
    M_{21} \space = \begin{bmatrix} 
    1&3&1 \\
    2&1&3 \\
    3&1&1 \\
  \end{bmatrix} \\ \\
\end{matrix} \\
$

$
Menggunakan \space Baris \space 2 = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} \\
$  

$
c_{21} = (-1)^{2+1} = (-1)^{2+1}det(
\begin{matrix}
  \begin{bmatrix}
    3&1 \\
    1&1
  \end{bmatrix}) 
\end{matrix} = -1.2
$  


$
c_{22} = (-1)^{2+2} = (-1)^{2+2}det
\begin{matrix}(
  \begin{bmatrix}
    1&1 \\
    3&1
  \end{bmatrix}) 
\end{matrix} = 1.-2
$  

$
c_{23} = (-1)^{2+3} = (-1)^{2+3}det
\begin{matrix}(
  \begin{bmatrix}
    1&3 \\
    3&1
  \end{bmatrix})
\end{matrix} = -1.-8
$  

$
a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} = 2.(-1).2 + 1.(1).-2 + 3.(-1).-8 \\ 
$  

$
det(M_{21}) \space = -4 + -2 +24 =  18
$  

Determinan $M_{21}$ adalah **18**  

**Determinan M22**  
Mencari determinan dari $M_{22}$ dengan Ekspansi kofaktor  
$
\begin{matrix} \\
 M_{22} \space  = \begin{bmatrix} 
    2&3&1 \\
    3&1&3 \\
    2&1&1 \\
  \end{bmatrix} \\ \\
\end{matrix} \\
$  


$
Menggunakan \space Baris \space 2 = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} 
$

$
c_{21} = (-1)^{2+1} = (-1)^{2+1} det
\begin{matrix}(
  \begin{bmatrix}
   3&1 \\
   1&1 
  \end{bmatrix})
\end{matrix} = -1.2
$  

$
c_{22} = (-1)^{2+2} = (-1)^{2+2} det 
\begin{matrix}(
  \begin{bmatrix}
   2&1 \\
   2&1
  \end{bmatrix})
\end{matrix} = 1.0
$  

$
c_{23} = (-1)^{2+3}= (-1)^{2+3} det
\begin{matrix}(
  \begin{bmatrix}
    2&3 \\
    2&1
  \end{bmatrix})
\end{matrix}   = -1.-4
$  

$
a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} = 3.(-1).2 + 1.(1).0 + 3.(-1).-4 
$  

$
det(M_{22}) \space= -6 + 0 - 12 =  6
$  
Determinan dari $M_{22}$ adalah **6** 

**Determinan M23**  
Mencari determinan dari $M_{23}$ dengan Ekspansi kofaktor  
$
\begin{matrix} 
 M_{23} \space = \begin{bmatrix} 
    2&1&1 \\
    3&2&3 \\
    2&3&1 \\
  \end{bmatrix} 
\end{matrix} 
$  

$
Menggunakan \space Baris \space 2 = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} \\
$  

$
c_{21} = (-1)^{2+1} = (-1)^{2+1} det
\begin{matrix}(
  \begin{bmatrix}
   1&1 \\
   3&1 
  \end{bmatrix})
\end{matrix}   = -1.-2
$  

$
c_{22} = (-1)^{2+2} = (-1)^{2+2} det 
\begin{matrix}(
  \begin{bmatrix}
   2&1 \\
   2&1
  \end{bmatrix})
\end{matrix}  = 1.0
$  

$
c_{23} = (-1)^{2+3} = (-1)^{2+3} det
\begin{matrix}(
  \begin{bmatrix}
    2&1 \\
    2&3
  \end{bmatrix})
\end{matrix}  = -1.4
$  

$
a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} = 3.(-1).-2 + 2.(1).0 + 3.(-1).4 \\ 
$  

$
det(M_{23}) \space = 6 + 0 - 12 = -12
$  
Determinan dari $M_{23}$ adalah **-12**  

**Determinan M24**  
Mencari determinan dari $M_{24}$ dengan Ekspansi kofaktor  
$
\begin{matrix} \\
  M_{24} \space = \begin{bmatrix} 
    2&1&3 \\
    3&2&1 \\
    2&3&1 \\
  \end{bmatrix} \\ \\
\end{matrix} \\
$  

$
Menggunakan \space Baris \space 2 = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} \\
$  

$
c_{21} = (-1)^{2+1} = (-1)^{2+1} det
\begin{matrix}(
  \begin{bmatrix}
   1&3 \\
   3&1 
  \end{bmatrix})
\end{matrix} = -1.-8
$  

$
c_{22} = (-1)^{2+2} = (-1)^{2+2} det 
\begin{matrix}(
  \begin{bmatrix}
   2&3 \\
   2&1
  \end{bmatrix})
\end{matrix} = 1.-4
$  

$
c_{23} = (-1)^{2+3} = (-1)^{2+3} det
\begin{matrix}(
  \begin{bmatrix}
    2&1 \\
    2&3
  \end{bmatrix})
\end{matrix} = -1.4
$  

$
a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} = 3.(-1).-8 + 2.(1).-4 + 1.(-1).4 \\ 
$  

$
det(M_{24}) \space  = 24 - 8 - 4 = 12
$  
Determinan dari $M_{24}$ adalah **12** 

**Langkah terakhir Mencari Determinan A**  
    
$
det(M_{21}) = 18 
$

$
det(M_{22}) = 6
$

$ 
det(M_{23}) = -6
$

$
det(M_{24}) = 12
$  

jadi :                              
  C21   =  $3 * (-1)^2+^1 -8$ =    24                                         
  C22   =  $2 * (-1)^2+^2 -4$ =    -8                                                  
  C23   =  $1 * (-1)^2+^3 4$  =    -4                                 

  $DetM34$    = 24 + -8 + -4 = 12

# jadi
$C31$     =     $4*(-1)^3+^1 18$      =   72                       
$C32$     =     $2*(-1)^3+^2 6$       =   -12              
$C33$     =     $3*(-1)^3+^3 -6$      =   -18         
$C34$     =     $2*(-1)^3+^4 12$      =   -24   
dapat disimpulkan bahwa                                                                                              
$Det matriks A$    =72 -12 -18 -12 = 18                                  


  
**Jadi Determinan dari Matriks A = 18**

**Kita akan membuktikanya dengan python apakah benar determinan A = 4**

In [1]:
import numpy as np

A = np.array([[2,1,3,1], [3,2,1,3], [4,2,3,2], [2,3,1,1]])
detA = np.linalg.det(A)
print("A: \n", A)
print()
print("Determinan A : ", round(detA))

A: 
 [[2 1 3 1]
 [3 2 1 3]
 [4 2 3 2]
 [2 3 1 1]]

Determinan A :  18
